apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
  namespace: azure-log-forwarding
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    k8s-app: fluent-bit-logging
  ports:
    - protocol: TCP
      port: 24224
      targetPort: 24224