  global:
    resolve_timeout: 5m
    smtp_smarthost: brighthousefinancial-com.mail.protection.outlook.com:25
    smtp_from: dev-osd-alerts@openshift.brighthousefinancial.com
    smtp_require_tls: false
  route:
    receiver: "default"
    routes:
    - receiver: critical_only
      match:
        severity: critical
      repeat_interval: 15m
    - receiver: deadmansswitch
      match:
        alertname: DeadMansSwitch
      repeat_interval: 5m
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 8h
  receivers:
  - name: "default"
    email_configs:
    - to: cj.meidlinger@brighthousefinancial.com
      send_resolved: true
  - name: "critical_only"
    email_configs:
    - to: cj.meidlinger@brighthousefinancial.com
    - to: VADER_DevOps@brighthousefinancial.com
      send_resolved: true
  - name: deadmansswitch
  templates: []

