---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    prometheus: federation-prometheus
  name: federation-prometheus-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - services
  - endpoints
  verbs:
  - list
  - get
  - watch
- apiGroups: [""]
  resources:
  - configmaps
  verbs:
  - list
  - get
  - watch
