apiVersion: v1
kind: Namespace
metadata:
  name: ossm

--- 
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  namespace: ossm
  name: ossm-e2e-encryption
spec:
  cluster:
    name: ossm-e2e-encryption
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  policy:
    type: Istiod
  telemetry:
    type: Istiod
  tracing:
    sampling: 10000
    type: Jaeger
  runtime:
    defaults:
      container:
        imagePullPolicy: Always
  proxy:
    accessLogging:
      file:
        name: /dev/stdout        
  security:
    identity:
      type: ThirdParty
      thirdParty:
        audience: istio-ca
  gateways:
    ingress: # istio-ingressgateway
      service:
        metadata:
            annotations:
                  service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
                  service.beta.kubernetes.io/aws-load-balancer-scheme: internal
                  service.beta.kubernetes.io/aws-load-balancer-private-ipv4-addresses: 10.201.0.199, 10.201.1.199, 10.201.2.199
                  service.beta.kubernetes.io/aws-load-balancer-type: external
        type: LoadBalancer
