kind: Deployment
apiVersion: apps/v1
metadata:
  name: http-https-echo
  namespace: echo-server
  labels:
    app: http-https-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-https-echo
  template:
    metadata:
      labels:
        app: http-https-echo
    spec:
      containers:
        - name: http-https-echo
          image: mendhak/http-https-echo:30
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
--- 
kind: Service
apiVersion: v1
metadata:
  name: http-https-echo
  namespace: echo-server
  labels:
    app: http-https-echo
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-private-ipv4-addresses: '10.201.0.199, 10.201.1.199, 10.201.2.199'
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-type: external
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
  type: LoadBalancer