---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: federated-monitor
  name: federated-prometheus
  namespace: openshift-monitoring
spec:
  endpoints:
  - interval: 30s
    scrapeTimeout: 30s
    port: web
    path: /federate
    honorLabels: true
    params:
      'match[]':
        - '{__name__=~".+"}'
    scheme: https
    # bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    # tlsConfig:
    #   caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
    #   serverName: prometheus-k8s.openshift-monitoring.svc.cluster.local
  namespaceSelector:
    matchNames:
    - openshift-monitoring
  selector:
    matchLabels:
      prometheus: "k8s"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    prometheus: federated-prometheus
  name: federated-prometheus-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - services
  - endpoints
  verbs:
  - list
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: federated-prometheus-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: federated-prometheus-role
subjects:
- kind: ServiceAccount
  name: prometheus-user-workload
  namespace: openshift-user-workload-monitoring