apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: thanos-receiver-grafana
  namespace: thanos-receiver
spec:
  basicAuth: true
  config:
    auth:
      disable_signout_menu: false
    auth.anonymous:
      enabled: false
    log:
      level: warn
      mode: console
    security:
      admin_password: secret
      admin_user: root
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
  ingress:
    enabled: true
---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: thanos-querier-datasource
  namespace: thanos-receiver
spec:
  datasources:
    - access: proxy
      editable: false
      isDefault: true
      jsonData:
        timeInterval: 5s
      name: prometheus
      type: prometheus
      url: 'http://thanos-querier.thanos-receiver.svc.cluster.local:9090'
  name: thanos-querier-datasource.yaml
---