apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: user-workload
  name: prometheus-user-workload-headless
  namespace: openshift-user-workload-monitoring
spec:
  ports:
  - name: metrics
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: prometheus
    prometheus: user-workload
  clusterIP: None